apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # コンテナ定義
      containers:
        - name: nginx
          image: zeusmyamada/jenkins-test:latest
          ports:
            - containerPort: 80
---
# Service(NodePort)の作成
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    app: nginx
  ports:
    - port: 80
  type: NodePort
