apiVersion: v1
kind: Pod
metadata:
  name: jenkins-test
spec:
  # コンテナ定義
  containers:
    - name: nginx-container
      image: zeusmyamada/jenkins-test
      ports:
        - containerPort: 80
      # ボリュームマウント
      volumeMounts:
        - name: cm-volume # ConfigMapのボリューム
          mountPath: /usr/share/nginx/html # マウントポイント
  # ボリューム定義
  volumes:
    - name: cm-volume
      configMap:
        name: cm-data # ConfigMapの名前を指定
---
# Service(NodePort)の作成
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    app: nginx-container
  ports:
    - port: 80
  type: NodePort
---
# ConfigMapの作成
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-data
data:
  hogehoge.html: |
    hogehoge
