apiVersion: v1
kind: Pod
metadata:
  name: jenkins-test
spec:
  # コンテナ定義
  containers:
    - name: nginx-container
      image: zeusmyamada/jenkins-test:latest
      ports:
        - containerPort: 80
---
# Service(NodePort)の作成
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    app: nginx-container
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
  type: NodePort
